### ISSUE TITLE
Crash during map generation

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#122]
```
Traceback (most recent call last):
  File "main.py", line 271, in <module>
    play_the_game()
  File "main.py", line 262, in play_the_game
    action(tsrd)
  File "main.py", line 172, in load_game
    camp.play()
  File "/home/almkglor/games/gearhead-caramel/gears/__init__.py", line 424, in play
    super(GearHeadCampaign, self).play()
  File "/home/almkglor/games/gearhead-caramel/pbge/campaign.py", line 107, in play
    exp.go()
  File "/home/almkglor/games/gearhead-caramel/game/exploration.py", line 469, in go
    if not self.order( self ):
  File "/home/almkglor/games/gearhead-caramel/game/exploration.py", line 95, in __call__
    keep_going = self.move_pc( exp, pc, self.path.results[self.step], True )
  File "/home/almkglor/games/gearhead-caramel/game/exploration.py", line 67, in move_pc
    wp.bump(exp.camp,pc)
  File "/home/almkglor/games/gearhead-caramel/game/content/ghplots/dd_main.py", line 362, in bump
    self.unlocked_use( camp )
  File "/home/almkglor/games/gearhead-caramel/game/content/ghplots/dd_main.py", line 356, in unlocked_use
    fx(camp)
  File "/home/almkglor/games/gearhead-caramel/game/content/adventureseed.py", line 46, in __call__
    nart.build()
  File "/home/almkglor/games/gearhead-caramel/pbge/plots.py", line 406, in build
    g.make()
  File "/home/almkglor/games/gearhead-caramel/pbge/randmaps/__init__.py", line 70, in make
    self.step_five( self.gb, self.archi ) # Render for self, then children
  File "/home/almkglor/games/gearhead-caramel/pbge/randmaps/rooms.py", line 66, in step_five
    r.step_five( gb, archi )
  File "/home/almkglor/games/gearhead-caramel/pbge/randmaps/rooms.py", line 62, in step_five
    self.build( gb, archi )
  File "/home/almkglor/games/gearhead-caramel/game/content/ghrooms.py", line 34, in build
    x = random.randint(self.area.left+3,self.area.right-4)
  File "/usr/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (10,10, 0)
```

**Comment by jwvhewitt** [comment]
Fixed.

**Comment by AmkG** [comment]
There is similar code in `MSRuinsRoom` as well, which I also encountered crashes on (didn't dump the traceback though).

https://github.com/jwvhewitt/gearhead-caramel/blob/fc650029500e9bd99c7e6cf929fd2b2abb54e144/game/content/ghrooms.py#L59-L60

You might want to review `ForestRoom` as well.
