### ISSUE TITLE
`KeyError: 'allied_faction'` during mission

### ISSUE THREAD

**Issue by AmkG** [jwvhewitt/gearhead-caramel#6]
```
Traceback (most recent call last):
  File "main.py", line 271, in <module>
  File "main.py", line 262, in play_the_game
  File "main.py", line 172, in load_game
  File "gears/__init__.py", line 390, in play
  File "pbge/campaign.py", line 107, in play
  File "game/exploration.py", line 474, in go
  File "game/exploration.py", line 389, in update_npcs
  File "game/exploration.py", line 351, in activate_foe
  File "game/combat/__init__.py", line 175, in activate_foe
  File "pbge/campaign.py", line 81, in check_trigger
  File "pbge/plots.py", line 269, in handle_trigger
  File "game/content/ghplots/dd_combatmission.py", line 72, in _eteam_ACTIVATETEAM
  File "game/ghdialogue/__init__.py", line 73, in start_conversation
  File "pbge/dialogue/__init__.py", line 141, in __init__
  File "pbge/dialogue/__init__.py", line 201, in build
  File "pbge/dialogue/__init__.py", line 154, in _get_dialogue_data
  File "pbge/plots.py", line 284, in get_dialogue_offers
  File "game/content/ghplots/dd_combatmission.py", line 77, in _commander_offers
KeyError: 'allied_faction'
```

Attached .sav files: [Keelsky.zip](https://github.com/jwvhewitt/gearhead-caramel/files/4482881/Keelsky.zip)

**Comment by AmkG** [comment]
More specifically: I complete the secure cargo sub-mission first, before fighting the commander, and the commander dialog crashes.

**Comment by AmkG** [comment]
Hmm even if I engage the commander first, the commander dialog crashes with the given `KeyError`.  `Python 2.7.17`.

**Comment by jwvhewitt** [comment]
Thanks for reporting the problem! It has been fixed.
